name:                jogo-da-velha
version:             0.1.0.0
github:              "UnBParadigmas2023-2/2023.2_G1_Funcional_"
license:             BSD3
author:              ["Pedro Jesus", "Sidney Lemes", "Lucas Caldas", "Rodrigo Santos", "Erick Santos", "Roddas Cabral", "Laura Oliveira", "Hellen Faria", "Debora Moreira"]
maintainer:          ["ro12062000@gmail.com"]
copyright:           "2023-2 UnBParadigmas"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/UnBParadigmas2023-2/2023.2_G1_Funcional_#readme>

dependencies:
- array
- base >= 4.7 && < 5
- gloss
- gloss-rendering

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  jogo-da-velha-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - jogo-da-velha

tests:
  jogo-da-velha-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - jogo-da-velha
